version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/nest"
    networks:
      - app_network

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db

networks:
  app_network:

volumes:
  mongo_data:
